### ISSUE TITLE
OpenChemistry cloning instruction lacks --recursive option

### ISSUE THREAD

**Issue by mss1451** [kbsezginel/nanocar-avogadro#8]
The first instruction here [https://kbsezginel.github.io/nanocar-avogadro/installation#linux](https://kbsezginel.github.io/nanocar-avogadro/installation#linux) is:

`git clone https://github.com/OpenChemistry/openchemistry.git`

But as written here [http://wiki.openchemistry.org/Build#Cloning_Repositories](http://wiki.openchemistry.org/Build#Cloning_Repositories) the `--recursive` option is necessary to include the sub modules otherwise the build fails at the very beginning.

**Comment by kbsezginel** [comment]
Good catch! Could you update the page accordingly and make a pull request?

**Comment by mss1451** [comment]
Done.

**Comment by kbsezginel** [comment]
Thanks, #9 closes this.
